name: Deploy to Staging (Moon) 🌕

on:
  push:
    branches:
      - moon
  pull_request:
    branches:
      - earth
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          if [ -z "${{ secrets.STAGING_SSH_KEY }}" ]; then
            echo "Error: STAGING_SSH_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.STAGING_HOST }}" ]; then
            echo "Error: STAGING_HOST secret is not set"
            exit 1
          fi
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.STAGING_HOST }}" 2>/dev/null > ~/.ssh/known_hosts || {
            echo "Error: Failed to scan host key for ${{ secrets.STAGING_HOST }}"
            exit 1
          }
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to staging
        env:
          SSH_HOST: ${{ secrets.STAGING_HOST }}
          SSH_USER: ${{ secrets.STAGING_USERNAME }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=accept-new ${SSH_USER}@${SSH_HOST} '
            cd /var/www/veganeiro-staging
            git pull origin moon
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d --build
            docker system prune -f
          '
